/-
`ssz-specs` conformance runner.

Fixtures: vendored from leanEthereum/ssz-specs commit
769485dd12c6aa13b72ba4498110d0a86a337e63, generated by
`uv run --group test fill tests/fillers/ssz` (generated, not committed
upstream). Unlike the leanSpec fixtures, each roundtrip case also carries
a `root` (`hash_tree_root`), and the suite includes decode-failure cases.

Checks per roundtrip case:
  1. encode: `enc (parse value) == serialized`;
  2. decode: `enc <$> dec serialized == ok serialized` (with 1 and the
     proven injectivity, this pins the decoded value to the original);
  3. htr: `htr (parse value) == root`.

Checks per decode-failure case (has `rejectionReason`):
  - `dec rawBytes` is `.error` (strict decoding rejects the input).

`Uint128` / `Uint256` are outside leanSpec's SSZ subset, so those cases
are skipped and counted (never silently dropped).
-/

import LeanSSZ
import Lean.Data.Json

open Lean (Json)
open LeanSSZ

abbrev P := Except String

/-! ## Primitive parsers -/

def hexNib (c : Char) : P Nat :=
  if '0' ≤ c ∧ c ≤ '9' then .ok (c.toNat - '0'.toNat)
  else if 'a' ≤ c ∧ c ≤ 'f' then .ok (c.toNat - 'a'.toNat + 10)
  else if 'A' ≤ c ∧ c ≤ 'F' then .ok (c.toNat - 'A'.toNat + 10)
  else .error s!"bad hex char {c}"

def hexToBytes (s : String) : P (List UInt8) := do
  let body : String := if s.startsWith "0x" then (s.drop 2).toString else s
  let cs := body.toList
  if cs.length % 2 ≠ 0 then throw "odd hex length"
  let rec go : List Char → P (List UInt8)
    | [] => .ok []
    | hi :: lo :: rest => do
      let h ← hexNib hi
      let l ← hexNib lo
      let tl ← go rest
      pure (UInt8.ofNat (h * 16 + l) :: tl)
    | _ => .error "odd hex length"
  go cs

def jField (j : Json) (k : String) : P Json := j.getObjVal? k

/-- Numbers reach us either as JSON numbers (vector/list elements) or as
decimal strings (top-level scalar uints). Accept both. -/
def pNat (j : Json) : P Nat :=
  match j.getNat? with
  | .ok n => .ok n
  | .error _ => do
    let s ← j.getStr?
    match s.toNat? with
    | some n => .ok n
    | none => .error s!"not a nat: {s}"

def pUint (bits : Nat) (j : Json) : P Nat := do
  let n ← pNat j
  if n < 2 ^ bits then pure n else throw s!"uint{bits} out of range"

def pU8  (j : Json) : P Uint8  := do pure (UInt8.ofNat  (← pUint 8 j))
def pU16 (j : Json) : P Uint16 := do pure (UInt16.ofNat (← pUint 16 j))
def pU32 (j : Json) : P Uint32 := do pure (UInt32.ofNat (← pUint 32 j))
def pU64 (j : Json) : P Uint64 := do pure (UInt64.ofNat (← pUint 64 j))

/-- Byte arrays: value is a bare `0x…` hex string. -/
def pBytesN (n : Nat) (j : Json) : P (BytesN n) := do
  let s ← j.getStr?
  let bs ← hexToBytes s
  if h : bs.length = n then
    pure ⟨⟨bs.toArray⟩, by simpa [ByteArray.size] using h⟩
  else throw s!"expected {n} bytes, got {bs.length}"

/-- Byte lists: value is `{ "data": "0x…" }`. -/
def pByteList (limit : Nat) (j : Json) : P (ByteList limit) := do
  let s ← (← jField j "data").getStr?
  let bs ← hexToBytes s
  if h : bs.length ≤ limit then pure ⟨bs, h⟩
  else throw "bytelist over limit"

def pDataArray (j : Json) : P (Array Json) := do
  (← jField j "data").getArr?

def pBoolList (j : Json) : P (List Bool) := do
  let arr ← pDataArray j
  arr.toList.mapM (·.getBool?)

def pBitvector (n : Nat) (j : Json) : P (Bitvector n) := do
  let bits ← pBoolList j
  if h : bits.length = n then pure ⟨bits, h⟩
  else throw s!"bitvector length mismatch: expected {n}, got {bits.length}"

def pBitlist (limit : Nat) (j : Json) : P (Bitlist limit) := do
  let bits ← pBoolList j
  if h : bits.length ≤ limit then pure ⟨bits, h⟩
  else throw "bitlist over limit"

def pSSZList {T : Type} (limit : Nat) (pe : Json → P T) (j : Json) :
    P (SSZList T limit) := do
  let arr ← pDataArray j
  let xs ← arr.toList.mapM pe
  if h : xs.length ≤ limit then pure ⟨xs, h⟩
  else throw "list over limit"

def pVector {T : Type} (n : Nat) (pe : Json → P T) (j : Json) :
    P (SSZVector T n) := do
  let arr ← pDataArray j
  let xs ← arr.toList.mapM pe
  if h : xs.toArray.size = n then pure ⟨xs.toArray, h⟩
  else throw "vector length mismatch"

/-! ## Case runners -/

/-- Roundtrip + HTR case: `T` must have a codec and a hash-tree-root. -/
def runCase {T : Type} [SSZCodec T] [HasHTR T] (pv : Json → P T)
    (val : Json) (ser root : List UInt8) : Option String :=
  match pv val with
  | .error e => some s!"value parse: {e}"
  | .ok v =>
    if enc v ≠ ser then some "encode mismatch"
    else match dec (T := T) ser with
      | .error _ => some "decode failed"
      | .ok v' =>
        if enc v' ≠ ser then some "decode/re-encode mismatch"
        else if (htr v).val.toList ≠ root then some "htr mismatch"
        else none

/-- Decode-failure case: strict decoding must reject `rawBytes`. -/
def runFailCase {T : Type} [SSZCodec T] (raw : List UInt8) : Option String :=
  match dec (T := T) raw with
  | .error _ => none
  | .ok _ => some "decode unexpectedly succeeded"

/-- Result of dispatching a case: pass/fail message, or an explicit skip. -/
inductive Outcome
  | ok
  | fail (msg : String)
  | skip (reason : String)

def toOutcome : Option String → Outcome
  | none => .ok
  | some m => .fail m

def dispatch (typeName : String) (val : Json) (ser root : List UInt8)
    (rawBytes : Option (List UInt8)) : Outcome :=
  -- Decode-failure cases carry `rejectionReason`; `rawBytes` is present.
  match rawBytes with
  | some raw =>
    match typeName with
    | "SmokeBitlist8" => toOutcome (runFailCase (T := Bitlist 8) raw)
    | _ => .skip s!"unhandled failure type {typeName}"
  | none =>
    match typeName with
    | "Boolean" => toOutcome (runCase (T := Boolean) (·.getBool?) val ser root)
    | "Uint8"   => toOutcome (runCase pU8  val ser root)
    | "Uint16"  => toOutcome (runCase pU16 val ser root)
    | "Uint32"  => toOutcome (runCase pU32 val ser root)
    | "Uint64"  => toOutcome (runCase pU64 val ser root)
    | "Uint128" => .skip "Uint128 outside leanSpec subset"
    | "Uint256" => .skip "Uint256 outside leanSpec subset"
    | "Bytes4"  => toOutcome (runCase (pBytesN 4)  val ser root)
    | "Bytes32" => toOutcome (runCase (pBytesN 32) val ser root)
    | "Bytes52" => toOutcome (runCase (pBytesN 52) val ser root)
    | "Bytes64" => toOutcome (runCase (pBytesN 64) val ser root)
    | "ByteList512KiB" =>
        toOutcome (runCase (T := ByteList512KiB) (pByteList (512 * 1024)) val ser root)
    | "SampleBitvector8"   => toOutcome (runCase (pBitvector 8)   val ser root)
    | "SampleBitvector64"  => toOutcome (runCase (pBitvector 64)  val ser root)
    | "BoundaryBitvector1"   => toOutcome (runCase (pBitvector 1)   val ser root)
    | "BoundaryBitvector7"   => toOutcome (runCase (pBitvector 7)   val ser root)
    | "BoundaryBitvector9"   => toOutcome (runCase (pBitvector 9)   val ser root)
    | "BoundaryBitvector255" => toOutcome (runCase (pBitvector 255) val ser root)
    | "BoundaryBitvector256" => toOutcome (runCase (pBitvector 256) val ser root)
    | "BoundaryBitvector257" => toOutcome (runCase (pBitvector 257) val ser root)
    | "SampleBitlist16"    => toOutcome (runCase (pBitlist 16)  val ser root)
    | "BoundaryBitlist256" => toOutcome (runCase (pBitlist 256) val ser root)
    | "SampleUint16Vector3" =>
        toOutcome (runCase (pVector 3 pU16) val ser root)
    | "SampleUint64Vector4" =>
        toOutcome (runCase (pVector 4 pU64) val ser root)
    | "SampleUint32List16" =>
        toOutcome (runCase (pSSZList 16 pU32) val ser root)
    | "SampleBytes32List8" =>
        toOutcome (runCase (pSSZList 8 (pBytesN 32)) val ser root)
    | "BoundaryUint64List32" =>
        toOutcome (runCase (pSSZList 32 pU64) val ser root)
    | _ => .fail s!"unknown type {typeName}"

def main : IO UInt32 := do
  let root : System.FilePath := "Tests/ssz-specs-fixtures"
  let files ← root.walkDir
  let mut pass := 0
  let mut fail := 0
  let mut skip := 0
  for f in files do
    if f.extension = some "json" then
      let text ← IO.FS.readFile f
      match Json.parse text with
      | .error e => IO.println s!"FAIL {f}: json parse {e}"; fail := fail + 1
      | .ok top =>
        let entries := top.getObj?.toOption.map (·.toArray) |>.getD #[]
        for ⟨caseName, body⟩ in entries do
          let parsed : P Outcome := do
            let tn ← (← jField body "typeName").getStr?
            let val ← jField body "value"
            let ser ← hexToBytes (← (← jField body "serialized").getStr?)
            let rootHex := ((← jField body "root").getStr?).toOption.getD ""
            let rootBytes ← if rootHex.isEmpty then pure [] else hexToBytes rootHex
            let rawBytes ← match (jField body "rawBytes").toOption with
              | some j => do pure (some (← hexToBytes (← j.getStr?)))
              | none => pure none
            pure (dispatch tn val ser rootBytes rawBytes)
          match parsed with
          | .error e => IO.println s!"FAIL {caseName}: {e}"; fail := fail + 1
          | .ok .ok => pass := pass + 1
          | .ok (.fail msg) => IO.println s!"FAIL {caseName}: {msg}"; fail := fail + 1
          | .ok (.skip reason) =>
              IO.println s!"SKIP {caseName}: {reason}"; skip := skip + 1
  IO.println s!"ssz-specs: {pass} passed, {fail} failed, {skip} skipped"
  pure (if fail = 0 then 0 else 1)
